name: CI/CD with Docker

on:
  push:
    branches: [cicd-test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Code checkout
      - uses: actions/checkout@v3

      # 2. application.yml 파일을 GitHub Secrets에서 가져와서 덮어쓰기
      - name: Create application.yml from Secrets
        run: |
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml

      # 3. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Set up Buildx with containerd driver
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          use-containerd: true

      # 5. Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/flowday:latest
            ${{ secrets.DOCKER_USERNAME }}/flowday:${{ github.sha }}
          labels: "org.opencontainers.image.title=flowday"

      # 6. Elastic Beanstalk 배포
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: flowday
          environment_name: Flowday-env
          version_label: docker-${{ github.run_id }}
          region: ap-northeast-2
          deployment_package: ./Dockerrun.aws.json  # Dockerrun.aws.json 파일 경로
