name: CI/CD with Docker

on:
  push:
    branches: [ cicd-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드를 체크아웃
      - uses: actions/checkout@v3

      # 2. application.yml 파일을 GitHub Secrets에서 가져와서 덮어쓰기
      - name: Create application.yml from Secrets
        run: |
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

      # 3. Docker 파일을 다운로드하고 압축 해제
      - name: Download docker.zip from S3 and unzip
        run: |
          aws s3 cp s3://flowday/docker.zip ./docker.zip
          unzip docker.zip -d ./docker

      # 4. manifest.yml 파일을 사용하여 필요한 설정 확인
      - name: Check manifest.yml
        run: |
          cat ./resources/environments/e-8ghjmvenjh/runtime/versions/manifest.yml

      # 5. Docker를 설정하고 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flowday:latest .

      # 7. Dockerrun.aws.json 생성
      - name: Generate Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.DOCKER_USERNAME }}/flowday:latest",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "5000"
              }
            ]
          }' > Dockerrun.aws.json

      # 8. Docker Hub에 이미지 푸시
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flowday:latest

      # 9. Elastic Beanstalk 배포
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: flowday
          environment_name: Flowday-env
          version_label: docker-${{ github.run_id }}
          region: ap-northeast-2
          deployment_package: Dockerrun.aws.json
